under construction ...

##Introduction

The following is an example of sympy in action. This example demonstrates the use of various sympy and mpmath functions, specifically the use of matrix algebra and integration techniques to solve an engineering problem i.e. the analysis of the stress, strain and displacement response of an elastic layered structure to imposed surface loads. Typically these problems are solved using finite element methods (FEM) but an analytical solution based on the Hankel transformation of the stress function has been in use since it was introduced by Burmister [1]. 



[1] Burmister, D.M (1945), The General Theory of Stresses and Displacements in Layered Systems, Journal of Applied Physics, Vol. 16, p.89-94

Various commercial codes: BISAR, ELSYM5, CIRCLY.     

      