under construction ...

Elastic Layer Analysis (ELA)
============================

Introduction
------------

The following is an example of SymPy in action. This example demonstrates the use of various SymPy functions, specifically the use of matrix algebra and integration techniques to solve an engineering problem i.e. the analysis of the stress, strain and displacement response of an elastic layered structure to imposed surface loads. Typically these problems are solved using finite element methods (FEM) but a simple numerical solution based on the Hankel transformation of a stress function has been in use since it was introduced by Burmister [1]_. 

Elastic layer analysis (ELA) is routinely used in pavement engineering for the design and evaluation of road and airport structures. As with any structure, roads are designed and constructed to carry surface loads - the heavier the load, the stronger the structure needed. Concrete pavements on interstate highways, for example, are durable structures that can withstand very high compressive loads but a thin layer of concrete has a relatively low flexural strength and must therefore be supported to prevent excessive bending. This is typically achieved by paving the concrete layer of top of a cemented or stabilized base layer. The base layer in turn may be placed on top of a strong granular subbase layer, which in turn covers the foundation or subgrade, which is usually the weakest layer in the structure. Building stronger layers on top of the subgrade serves to protect it from excessive deformation. Figure 1 illustrates a typical pavement structure. 

[Figure 1 here]

For the elastic analysis of the pavement structure shown in Figure 1, the different layers are assumed to be homogeneous and isotropic. The materials used in each layer are defined by elastic parameters i.e. Young's modulus (\( E \)) and Poisson's ratio (\( \nu \)). Each layer has a finite thickness except the lowest subgrade layer, which is assumed to have an infinite thickness. The nature of the interface between successive layers dictates how stresses and displacements are transferred from one layer to another. For the purpose of this example, full-friction between the layers is assumed, therefore shear stresses and lateral displacements at the lower interface of any layer are equal to those at the top interface of the underlying layer.

Problem Formulation
-------------------

Stresses and displacements written to show the Hankel form are:
\[\sigma_{z}=\int_{0}^{\infty}\xi^{2}\left(\left(-A\xi+C\left(1-2\nu-\xi z\right)\right)e^{\xi z}+\left(B\xi+D\left(1-2\nu+\xi z\right)\right)e^{-\xi z}\right)\\mathrm{J}_0\left(r\xi\right)\xi\,d\xi\]
\[\tau_{rz}=\int_{0}^{\infty}\xi^{2}\frac{\\mathrm{J}_1\left(r\xi\right)}{\\mathrm{J}_0\left(r\xi\right)}\left(\left(A\xi+C\left(2\nu+\xi z\right)\right)e^{\xi z}+\left(B\xi+D\left(1-2\nu+\xi z\right)\right)e^{-\xi z}\right)\\mathrm{J}_0\left(r\xi\right)\xi\,d\xi\]
\[w=\frac{1+\nu}{E}\int_{0}^{\infty}\xi\left(\left(-A\xi+C\left(2-4\nu-\xi z\right)\right)e^{\xi z}-\left(B\xi+D\left(2-4\nu+\xi z\right)\right)e^{- \xi z}\right)\\mathrm{J}_0\left(r\xi\right)\xi\,d\xi\]
\[u=\frac{1+\nu}{E}\int_{0}^{\infty}\xi\frac{\\mathrm{J}_1\left(r\xi\right)}{\\mathrm{J}_0\left(r\xi\right)}\left(\left(A\xi+C\left(1+\xi z\right)\right)e^{\xi z}-\left(B\xi-D\left(1-\xi z\right)\right)e^{-\xi z}\right)\\mathrm{J}_0\left(r\xi\right)\xi\,d\xi\]

\(\sigma_{z}\), \(\tau_{rz}\)
    vertical compressive and shear stress
\(u\), \(w\)
    lateral and vertical displacement
\(\\mathrm{J}_0, \\mathrm{J}_1\)
    Bessel functions of order 0 and 1, respectively.
\(\xi\), \(r\), \(z\)
    Hankel parameter, radial position in cylindrical coordinates and vertical position
\(A,B,C,D\)
    integration constants

The *unknowns* in the stress and displacement equations are the four integration constants. These may be determined by applying boundary conditions. 

Boundary Conditions
^^^^^^^^^^^^^^^^^^^

The boundaries of the elastic layer system include the surface, interfaces between the layers and the infinite lowest layer. 

**Surface.** For the purpose of this example it is assumed that the loads imposed on the system are circular surface loads defined by a radius \(a\) and a uniform pressure \(p\) - the circular imprint simulates the impression of vehicle tyres. If only a vertical uniformly distributed circular load is considered, on the surface beneath the tire (\(r\leq a\)), \(\sigma_{z}=-q\) and \(\tau_{rz}=0\). In the Hankel domain, the load may be determined as:
\[q=\int_{0}^{\infty}rp\\mathrm{J}_0\left(\xi r\right)\,dr=\frac{pa}{\xi}\\mathrm{J}_1\left(\xi a\right)\]

**Interlayers.** As indicated previously, with full friction, to ensure equilibrium, stresses and displacements at the interlayers are equal:
\[\sigma_{z}^{i}\left(r,h_{i}\right)=\sigma_{z}^{i+1}\left(r,0\right)\]
\[\tau_{rz}^{i}\left(r,h_{i}\right)=\tau_{rz}^{i+1}\left(r,0\right)\]
\[u_{r}^{i}\left(r,h_{i}\right)=u_{r}^{i+1}\left(r,0\right)\]
\[u_{z}^{i}\left(r,h_{i}\right)=u_{z}^{i+1}\left(r,0\right)\]

**Infinite lower layer.** All stresses and displacements approach zero at infinite depth (\(z\rightarrow\infty\)). It can be shown that this implies that the integration constants \(A\) and \(C\) for this layer are zero.

Applying the boundary conditions allows the integration constants to be solved. Depending on the number of layers (\(n\)) in the system, the number of equations to solve is \(4n-2\). The solved constants may then be substituted into the stress and displacement equations, which are integrated to determine response to surface loads at specific evaluation positions (\(r\) and \(z\)). To demonstrate the process, consider a single layer subjected to a single circular load.

Single layer solution
---------------------

Applying the problem formulation and boundary conditions outlined above, the following code listing   

```python
from sympy import Symbol,Matrix,exp,sqrt,pi

xi=Symbol('xi')     # Bessel parameter
j0=Symbol('j0')     # Bessel function J0
j1=Symbol('j1')     # Bessel function J1
q=Symbol('q')       # Tyre pressure
a=Symbol('a')       # Tyre radius
nu0=Symbol('nu0')   # Poisson's ratio of layer

def hsz(z,nu):
    """
    Constants for Hankel transformed normal stress
    
    """ 
    a1=exp(xi*z)
    b1=-exp(-xi*z)
    c1=-(1-2*nu-xi*z)*exp(xi*z)
    d1=-(1-2*nu+xi*z)*exp(-xi*z)
    return a1,b1,c1,d1

def htrz(z,nu):
    """
    Constants for Hankel transformed shear stress
    
    """ 
    a2=exp(xi*z)
    b2=exp(-xi*z)
    c2=(2*nu+xi*z)*exp(xi*z)
    d2=-(2*nu-xi*z)*exp(-xi*z)
    return a2,b2,c2,d2

def s_z(r,z,nu,A,B,C,D):
    """
    Normal stress function
    
    """
    if r==0:
        return (A-C*(1-2*nu-xi*z))*exp(xi*z)-(B+D*(1-2*nu+xi*z))*exp(-xi*z)
    else:
        return ((A-C*(1-2*nu-xi*z))*exp(xi*z)-(B+D*(1-2*nu+xi*z))*exp(-xi*z))*j0(r*xi)

# Apply boundary condition for surface load
a1,b1,c1,d1=hsz(0,nu0)
a2,b2,c2,d2=htrz(0,nu0)

# For this single infinite layer the integration constants A and C are zero.
P=Matrix([[b1,d1],[b2,d2]])
R=Matrix(2,1,[1,0])
B,D=P.LUsolve(R)
```
     

.. [1] Burmister, D.M (1945), The General Theory of Stresses and Displacements in Layered Systems, Journal of Applied Physics, Vol. 16, p.89-94
