GSoC 2011 Report
================

This is our SymPy GSoC 2011 report.  This was our first year as an official mentoring organization for the program.  In previous years, students worked for SymPy under the umbrella of other organizations.  See http://www.google-melange.com/ for more information about Google Summer of Code.

We accepted nine students, listed below. All nine students were successful in the program.

The application is a draft of the application for each student that they posted on the wiki.  It may or may not be exactly the same as the final application that was submitted.

The students updated their blogs weekly throughout the summer with their progress, and may continue to write posts beyond the program.

Each student has written a detailed report on his project, which is linked to under the **Report** column in the table below.

You can find links to reports for previous years for GSoC at http://code.google.com/p/sympy/wiki/GSoC (TODO: Move all these pages to the GitHub wiki).

Accepted Students
-----------------

.. list-table::
   :header-rows: 1

   * - Proposal
     - Student
     - Mentor
     - Application
     - Blog
     - Report
   * - Definite Integration using Meijer G-functions
     - Tom Bachmann
     - Aaron Meurer
     - [[GSoC 2011 Application Tom Bachmann: Definite Integration|GSoC-2011-Application-Tom-Bachmann:-Definite-Integration]]
     - http://nessgrh.wordpress.com/
     - [[GSoC 2011 Report Tom Bachmann: Definite Integration|GSoC-2011-Report-Tom-Bachmann:-Definite-Integration]]
   * - PyDy
     - Gilbert Gede
     - Luke Peterson
     - [[GSoC 2011 Application Gilbert Gede: PyDy|GSoC-2011-Application-Gilbert-Gede:-PyDy]]
     - http://gilbertgede.wordpress.com/
     - [[GSoC 2011 Report Gilbert Gede: PyDy|GSoC-2011-Report-Gilbert-Gede:-PyDy]]
   * - Position and Momentum Bases for Quantum Mechanics
     - Tomo Lazovich
     - Brian Granger
     - [[GSoC 2011 Application Tomo Lazovich: Position and Momentum Bases for QM|GSoC-2011-Application-Tomo-Lazovich:-Position-and-Momentum-Bases-for-QM]]
     - http://lazovichsympy.wordpress.com/
     - [[GSoC 2011 Report Tomo Lazovich: Position and Momentum Bases for QM|GSoC-2011-Report-Tomo-Lazovich:-Position-and-Momentum-Bases-for-QM]]
   * - Combinatorics package for Sympy
     - Saptarshi Mandal
     - Christian Muise
     - [[GSoC 2011 Application Saptarshi Mandal: Combinatorics package for Sympy|GSoC-2011-Application-Saptarshi-Mandal:-Combinatorics-package-for-Sympy]]
     - http://saptman.wordpress.com/
     - [[GSoC 2011 Report Saptarshi Mandal: Combinatorics package for Sympy|GSoC-2011-Report-Saptarshi-Mandal:-Combinatorics-package-for-Sympy]]
   * - Symbolic Linear Algebra
     - Sherjil Ozair
     - Vinzent Steinberg
     - [[GSoC 2011 Application Sherjil Ozair: Symbolic Linear Algebra|GSoC-2011-Application-Sherjil-Ozair:-Symbolic-Linear-Algebra]]
     - http://sherjilozair.wordpress.com/
     - [[GSoC 2011 Report Sherjil Ozair: Symbolic Linear Algebra|GSoC-2011-Report-Sherjil-Ozair:-Symbolic-Linear-Algebra]] **(Not finished yet)**
   * - Porting to Python 3
     - Vladimir Peric
     - Ronan Lamy
     - [[GSoC 2011 Application: Vladimir Peric: Porting to Python 3|GSoC-2011-Application:-Vladimir-Perić:-Porting-to-Python-3]]
     - http://vperic.blogspot.com/
     - [[GSoC 2011 Report: Vladimir Peric: Porting to Python 3|GSoC-2011-Report:-Vladimir-Peric:-Porting-to-Python-3]] **(Not finished yet)**
   * - SymPy Stats: Random Variables
     - Matthew Rocklin
     - Andy Terrel
     - [[GSoC 2011 Application Matthew Rocklin: Random Variables|GSoC-2011-Application-Matthew-Rocklin:-Random-Variables]]
     - http://sympystats.wordpress.com/
     - [[GSoC 2011 Report Matthew Rocklin: Random Variables|GSoC-2011-Report-Matthew-Rocklin:-Random-Variables]]
   * - Symbolic Clebsch-Gordon coefficients/Wigner symbols and Implementing Addition of Spin Angular Momenta
     - Sean Vig
     - Ondřej Čertík
     - [[GSoC 2011 Application Sean Vig Symbolic Clebsch-Gordon coefficients:Wigner symbols and Implementing Addition of Spin Angular Momenta|GSoC-2011-Application-Sean-Vig-Symbolic-Clebsch-Gordon-coefficients:Wigner-symbols-and-Implementing-Addition-of-Spin-Angular-Momenta]]
     - http://seanvig.blogspot.com/
     - [[GSoC 2011 Report Sean Vig Symbolic Clebsch-Gordon coefficients:Wigner symbols and Implementing Addition of Spin Angular Momenta|GSoC-2011-Report-Sean-Vig-Symbolic-Clebsch-Gordon-coefficients:Wigner-symbols-and-Implementing-Addition-of-Spin-Angular-Momenta]]
   * - Implementing F5
     - Jeremias Yehdegho
     - Mateusz Paprocki
     - [[GSoC 2011 Application Jeremias Yehdegho: Implementing F5|GSoC-2011-Application-Jeremias-Yehdegho:-Implementing-F5]]
     - https://f1728.wordpress.com/
     - [[GSoC 2011 Report Jeremias Yehdegho: Implementing F5|GSoC-2011-Report-Jeremias-Yehdegho:-Implementing-F5]] **(Not finished yet)**

More Stuff
----------

Traffic
^^^^^^^

`Traffic <https://github.com/sympy/sympy/graphs/traffic>`_ data for March at github.  Google announced that SymPy was a mentoring organization on March 18, 2011.

.. image:: github_gsoc_2011_traffic.png

Forks
^^^^^

During the month of March 2011, SymPy was the number 1 forked Python project on GitHub, according to https://github.com/languages/Python.